### ISSUE TITLE
[18084] Failed to execute script DFIRtriage-v4-pub

### ISSUE THREAD

**Issue by solomyr** [travisfoley/dfirtriage#8]
Hello, 

I did minor changes to the code, but did not affect the main functions. I used pyinstaller -F  to create the executable on windows 10x64. When I run the exe here is what I get:

```
C:\Program Files\Python36\Scripts\dist>DFIRtriage-v4-pub.exe

#######################################################
#                                                     #
#  (     (    (   (                                   #
#  )\ )  )\ ) )\ ))\ )    *   )                       #
# (()/( (()/((()/(()/(  ` )  /((  (     ) (  (    (   #
#  /(_)) /(_))/(_))(_))  ( )(_))( )\ ( /( )\))(  ))\  #
# (_))_ (_))_(_))(_))   (_(_()|()((_))(_)|(_))\ /((_) #
#  |   \| |_ |_ _| _ \  |_   _|((_|_|(_)_ (()(_|_))   #
#  | |) | __| | ||   /    | | | '_| / _` / _` |/ -_)  #
#  |___/|_|  |___|_|_\    |_| |_| |_\__,_\__, |\___|  #
#                                        |___/        #
#                    Version 4.0.0                    #
#                                                     #
#######################################################


[+] Has Local Admin rights... [YES]

[+] Setting up environment...

Traceback (most recent call last):
  File "DFIRtriage-v4-pub.py", line 731, in <module>
  File "DFIRtriage-v4-pub.py", line 125, in env_setup
  File "zipfile.py", line 1113, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\solomyr\\AppData\\Local\\Temp\\_MEI34162/core.ir/\\core.ir'
[18084] Failed to execute script DFIRtriage-v4-pub
```
Here is the bundle_dir getting assigned:

```
if getattr(sys, 'frozen', False):
    BUNDLE_DIR = sys._MEIPASS + "/core.ir/"

else:
    BUNDLE_DIR = os.path.dirname(os.path.abspath(__file__)) + "/data"
```
If I remove +"/core.ir/"

```
if getattr(sys, 'frozen', False):
    BUNDLE_DIR = sys._MEIPASS
else:
    BUNDLE_DIR = os.path.dirname(os.path.abspath(__file__)) + "/data"
```
I get the following error:

```
C:\Program Files\Python36\Scripts\dist>DFIRtriage-v4-pub.exe

#######################################################
#                                                     #
#  (     (    (   (                                   #
#  )\ )  )\ ) )\ ))\ )    *   )                       #
# (()/( (()/((()/(()/(  ` )  /((  (     ) (  (    (   #
#  /(_)) /(_))/(_))(_))  ( )(_))( )\ ( /( )\))(  ))\  #
# (_))_ (_))_(_))(_))   (_(_()|()((_))(_)|(_))\ /((_) #
#  |   \| |_ |_ _| _ \  |_   _|((_|_|(_)_ (()(_|_))   #
#  | |) | __| | ||   /    | | | '_| / _` / _` |/ -_)  #
#  |___/|_|  |___|_|_\    |_| |_| |_\__,_\__, |\___|  #
#                                        |___/        #
#                    Version 4.0.0                    #
#                                                     #
#######################################################


[+] Has Local Admin rights... [YES]

[+] Setting up environment...

Traceback (most recent call last):
  File "DFIRtriage-v4-pub.py", line 730, in <module>
  File "DFIRtriage-v4-pub.py", line 124, in env_setup
  File "zipfile.py", line 1113, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\solomyr\\AppData\\Local\\Temp\\_MEI56522\\core.ir'
[9100] Failed to execute script DFIRtriage-v4-pub
```

**Comment by Brewcmas** [comment]
> Dependencies
> The tool repository contains the full toolset required for proper execution and is packed into a single a single file named “core.ir”. This “.ir” file is the only required dependency of DFIRtriage when running in Python and should reside in a directory named data, (ie. "./data/core.ir"). The compiled version of DFIRtriage has the full toolset embedded and does not require the addition of the "./data/core.ir" file. NOTE: TZWorks utilities are no longer utilized.

Based on the main information - would be able to take the core.ir from the "./data/core.ir" and place it in the "\AppData\\Local\\Temp\\_MEI56522\\" directory instead?

**Comment by solomyr** [comment]
Before running the compiler (pyinstaller) there is no folder \AppData\Local\Temp\_MEI56522\. It appears to me that _MEI56522 is randomly generated upon executing the standalone exe. And the folder is always different with randomly generated name like _MEIXXXXX.

**Comment by travisfoley** [comment]
All outstanding issues should be resolved in v5.  Closing.
